insert into AUTHORS (id, first_name, last_name) values (1, 'Gregoire', 'Mews');
insert into AUTHORS (id, first_name, last_name) values (2, 'Aldin', 'Bolderson');
insert into AUTHORS (id, first_name, last_name) values (3, 'Minette', 'Baybutt');
insert into AUTHORS (id, first_name, last_name) values (4, 'Hugibert', 'Loxston');
insert into AUTHORS (id, first_name, last_name) values (5, 'Starla', 'Besson');
insert into AUTHORS (id, first_name, last_name) values (6, 'Maggee', 'Blodget');
insert into AUTHORS (id, first_name, last_name) values (7, 'Evey', 'Aleksich');
insert into AUTHORS (id, first_name, last_name) values (8, 'Terrel', 'Dabney');
insert into AUTHORS (id, first_name, last_name) values (9, 'Dario', 'Leppard');
insert into AUTHORS (id, first_name, last_name) values (10, 'Vicky', 'Glassopp');
insert into AUTHORS (id, first_name, last_name) values (11, 'Jilli', 'Douris');
insert into AUTHORS (id, first_name, last_name) values (12, 'Theodore', 'Robke');
insert into AUTHORS (id, first_name, last_name) values (13, 'Orton', 'Bill');
insert into AUTHORS (id, first_name, last_name) values (14, 'Ferdie', 'Moan');
insert into AUTHORS (id, first_name, last_name) values (15, 'Arline', 'Barkshire');
insert into AUTHORS (id, first_name, last_name) values (16, 'Beniamino', 'Sleford');
insert into AUTHORS (id, first_name, last_name) values (17, 'Waylon', 'Geratasch');
insert into AUTHORS (id, first_name, last_name) values (18, 'Aubrie', 'Hearley');
insert into AUTHORS (id, first_name, last_name) values (19, 'Dosi', 'Richardes');
insert into AUTHORS (id, first_name, last_name) values (20, 'Giacopo', 'Wimpenny');
insert into BOOKS (id, title, genre, author) values (1, 'Road to Ruin, The', 'Drama', 14);
insert into BOOKS (id, title, genre, author) values (2, 'Fantasia', 'Animation|Children|Fantasy|Musical', 3);
insert into BOOKS (id, title, genre, author) values (3, 'Cinderella', 'Animation|Children|Fantasy|Romance', 19);
insert into BOOKS (id, title, genre, author) values (4, 'Tracy Morgan: Black and Blue', 'Comedy', 7);
insert into BOOKS (id, title, genre, author) values (5, '44 Inch Chest', 'Crime|Drama', 6);
insert into BOOKS (id, title, genre, author) values (6, 'Idol of the Crowds', 'Drama|Romance', 15);
insert into BOOKS (id, title, genre, author) values (7, 'Gory Gory Hallelujah', 'Comedy|Fantasy|Horror', 2);
insert into BOOKS (id, title, genre, author) values (8, 'To Cross the Rubicon', 'Drama', 6);
insert into BOOKS (id, title, genre, author) values (9, 'Stationmaster Is on Fire - The Movie, That Is!, The (Stinsen brinner... filmen alltså)', 'Comedy|Musical', 19);
insert into BOOKS (id, title, genre, author) values (10, 'Mea Maxima Culpa: Silence in the House of God', 'Documentary', 17);
insert into BOOKS (id, title, genre, author) values (11, 'Direct from Brooklyn', '(no genres listed)', 1);
insert into BOOKS (id, title, genre, author) values (12, 'Christmas Story (Joulutarina)', 'Children|Drama|Fantasy', 6);
insert into BOOKS (id, title, genre, author) values (13, 'Naked Jungle, The', 'Adventure|Drama', 4);
insert into BOOKS (id, title, genre, author) values (14, 'En på miljonen', '(no genres listed)', 7);
insert into BOOKS (id, title, genre, author) values (15, 'Calcium Kid, The', 'Comedy', 19);
insert into BOOKS (id, title, genre, author) values (16, 'Le ultime ore di una vergine', '(no genres listed)', 11);
insert into BOOKS (id, title, genre, author) values (17, 'La montaña rusa', 'Comedy|Romance', 9);
insert into BOOKS (id, title, genre, author) values (18, 'Julie', 'Thriller', 1);
insert into BOOKS (id, title, genre, author) values (19, 'Electrick Children', 'Drama', 14);
insert into BOOKS (id, title, genre, author) values (20, 'Making Plans for Lena (Non ma fille, tu n''iras pas danser)', 'Drama', 18);
insert into BOOKS (id, title, genre, author) values (21, 'American Promise', 'Documentary', 9);
insert into BOOKS (id, title, genre, author) values (22, 'Out-of-Towners, The', 'Comedy', 13);
insert into BOOKS (id, title, genre, author) values (23, 'East, West, East: The Final Sprint', 'Comedy|Drama', 2);
insert into BOOKS (id, title, genre, author) values (24, 'The Hearse', 'Drama|Horror|Mystery', 11);
insert into BOOKS (id, title, genre, author) values (25, 'Let It Snow', 'Comedy|Romance', 19);
insert into BOOKS (id, title, genre, author) values (26, 'Stargate', 'Action|Adventure|Sci-Fi', 18);
insert into BOOKS (id, title, genre, author) values (27, 'Get Carter', 'Action|Crime|Drama|Thriller', 1);
insert into BOOKS (id, title, genre, author) values (28, 'Roman de gare', 'Drama', 5);
insert into BOOKS (id, title, genre, author) values (29, 'Steel Toes', 'Crime|Drama', 16);
insert into BOOKS (id, title, genre, author) values (30, 'Cold Fish (Tsumetai nettaigyo)', 'Drama|Thriller', 19);
insert into BOOKS (id, title, genre, author) values (31, 'President''s Man, The', 'Action|Adventure|Thriller', 8);
insert into BOOKS (id, title, genre, author) values (32, 'Mercredi, folle journée!', 'Comedy|Drama', 6);
insert into BOOKS (id, title, genre, author) values (33, 'Far From Home: The Adventures of Yellow Dog', 'Adventure|Children', 4);
insert into BOOKS (id, title, genre, author) values (34, 'Emperor''s New Clothes, The', 'Comedy', 3);
insert into BOOKS (id, title, genre, author) values (35, 'The Monkey King', 'Action|Adventure|Children|IMAX', 17);
insert into BOOKS (id, title, genre, author) values (36, 'My Way to Olympia (Mein Weg nach Olympia)', 'Documentary', 7);
insert into BOOKS (id, title, genre, author) values (37, 'Dish & the Spoon, The', 'Comedy|Drama|Romance', 11);
insert into BOOKS (id, title, genre, author) values (38, 'I Am David', 'Drama', 6);
insert into BOOKS (id, title, genre, author) values (39, 'After Fall, Winter', 'Drama', 3);
insert into BOOKS (id, title, genre, author) values (40, 'Manchurian Candidate, The', 'Thriller', 5);
insert into BOOKS (id, title, genre, author) values (41, 'Less is More (Menos es más)', 'Comedy', 9);
insert into BOOKS (id, title, genre, author) values (42, 'Lone Wolf McQuade', 'Action', 6);
insert into BOOKS (id, title, genre, author) values (43, 'Hurry Sundown', 'Drama', 7);
insert into BOOKS (id, title, genre, author) values (44, 'Goal II: Living the Dream', 'Action|Drama', 10);
insert into BOOKS (id, title, genre, author) values (45, 'Barney''s Version', 'Drama', 10);
insert into BOOKS (id, title, genre, author) values (46, 'Quartet', 'Comedy|Drama', 4);
insert into BOOKS (id, title, genre, author) values (47, 'Fatal Attraction', 'Drama|Thriller', 7);
insert into BOOKS (id, title, genre, author) values (48, 'Fat, Sick & Nearly Dead 2', 'Documentary', 20);
insert into BOOKS (id, title, genre, author) values (49, 'Condition Red (Beyond the Law)', 'Action|Drama|Thriller', 1);
insert into BOOKS (id, title, genre, author) values (50, 'Gunner Palace', 'Documentary|War', 17);
insert into BOOKS (id, title, genre, author) values (51, 'What Richard Did', 'Drama', 10);
insert into BOOKS (id, title, genre, author) values (52, 'Paulie', 'Adventure|Children|Comedy', 4);
insert into BOOKS (id, title, genre, author) values (53, 'Shivers (They Came from Within)', 'Drama|Horror|Sci-Fi', 11);
insert into BOOKS (id, title, genre, author) values (54, 'Great Mouse Detective, The', 'Action|Animation|Children|Crime', 17);
insert into BOOKS (id, title, genre, author) values (55, 'Jumping the Broom', 'Comedy', 3);
insert into BOOKS (id, title, genre, author) values (56, 'Down Terrace', 'Comedy|Crime|Drama', 19);
insert into BOOKS (id, title, genre, author) values (57, 'Lethal Weapon 3', 'Action|Comedy|Crime|Drama', 13);
insert into BOOKS (id, title, genre, author) values (58, 'I Was A Communist for the FBI', 'Drama|Film-Noir|Thriller', 7);
insert into BOOKS (id, title, genre, author) values (59, 'Cold Comfort Farm', 'Comedy', 2);
insert into BOOKS (id, title, genre, author) values (60, 'Home Page', 'Documentary', 15);
insert into BOOKS (id, title, genre, author) values (61, 'Bill Hicks: Revelations', 'Comedy', 4);
insert into BOOKS (id, title, genre, author) values (62, 'Life and Debt', 'Documentary', 8);
insert into BOOKS (id, title, genre, author) values (63, 'Hybrid', 'Documentary', 5);
insert into BOOKS (id, title, genre, author) values (64, 'Send Me No Flowers', 'Comedy|Romance', 8);
insert into BOOKS (id, title, genre, author) values (65, 'Fast and the Furious: Tokyo Drift, The (Fast and the Furious 3, The)', 'Action|Crime|Drama|Thriller', 14);
insert into BOOKS (id, title, genre, author) values (66, 'Cannonball Run, The', 'Action|Comedy', 5);
insert into BOOKS (id, title, genre, author) values (67, 'Railway Man, The', 'Drama', 20);
insert into BOOKS (id, title, genre, author) values (68, 'Dragon Ball Z: Bojack Unbound (Doragon bôru Z 9: Ginga girigiri!! Butchigiri no sugoi yatsu)', 'Action|Adventure|Animation|Fantasy', 11);
insert into BOOKS (id, title, genre, author) values (69, 'Animal, The', 'Comedy', 11);
insert into BOOKS (id, title, genre, author) values (70, 'A Phantasy', 'Animation', 13);
insert into BOOKS (id, title, genre, author) values (71, 'MacGyver: Trail to Doomsday', 'Action|Adventure', 1);
insert into BOOKS (id, title, genre, author) values (72, 'Leo''s Room (Cuarto de Leo, El)', 'Drama', 16);
insert into BOOKS (id, title, genre, author) values (73, 'Ulysses', 'Drama', 1);
insert into BOOKS (id, title, genre, author) values (74, 'Nice Guys Sleep Alone', 'Comedy|Romance', 7);
insert into BOOKS (id, title, genre, author) values (75, 'Thale', 'Action|Drama|Horror|Mystery', 19);
insert into BOOKS (id, title, genre, author) values (76, 'Long Way Round', 'Adventure|Documentary', 7);
insert into BOOKS (id, title, genre, author) values (77, 'Four Daughters', 'Drama|Romance', 8);
insert into BOOKS (id, title, genre, author) values (78, 'Hurt', 'Drama|Horror|Thriller', 15);
insert into BOOKS (id, title, genre, author) values (79, 'Sexy Beast', 'Comedy|Crime|Drama', 1);
insert into BOOKS (id, title, genre, author) values (80, 'Moth, The (Cma)', 'Drama', 5);
insert into BOOKS (id, title, genre, author) values (81, 'Love and Pain and the Whole Damn Thing', 'Comedy|Drama', 17);
insert into BOOKS (id, title, genre, author) values (82, 'Blackout', 'Action|Thriller', 19);
insert into BOOKS (id, title, genre, author) values (83, 'Blind Chance (Przypadek)', 'Drama', 8);
insert into BOOKS (id, title, genre, author) values (84, 'Live Wire', 'Action', 15);
insert into BOOKS (id, title, genre, author) values (85, 'Expendables 3, The', 'Action|Adventure', 6);
insert into BOOKS (id, title, genre, author) values (86, 'Saphead, The', 'Comedy', 3);
insert into BOOKS (id, title, genre, author) values (87, 'Takers', 'Action|Crime|Thriller', 15);
insert into BOOKS (id, title, genre, author) values (88, 'Book of Shadows: Blair Witch 2', 'Crime|Horror|Mystery|Thriller', 7);
insert into BOOKS (id, title, genre, author) values (89, 'Frankie Starlight', 'Drama|Romance', 15);
insert into BOOKS (id, title, genre, author) values (90, 'War Zone, The', 'Drama|Thriller', 5);
insert into BOOKS (id, title, genre, author) values (91, 'Full Metal Jacket', 'Drama|War', 12);
insert into BOOKS (id, title, genre, author) values (92, 'Home of the Brave', 'Drama', 12);
insert into BOOKS (id, title, genre, author) values (93, 'Django 2: Django Strikes Again', 'Western', 10);
insert into BOOKS (id, title, genre, author) values (94, 'Grin Without a Cat, A (Fond de l''air est rouge, Le)', 'Documentary', 3);
insert into BOOKS (id, title, genre, author) values (95, 'What Will You Do When You Catch Me? (Co mi zrobisz jak mnie zlapiesz?)', 'Comedy|Crime', 2);
insert into BOOKS (id, title, genre, author) values (96, 'Death at a Funeral', 'Comedy', 10);
insert into BOOKS (id, title, genre, author) values (97, 'Suur Tõll', '(no genres listed)', 12);
insert into BOOKS (id, title, genre, author) values (98, 'Two Mules for Sister Sara', 'Comedy|War|Western', 16);
insert into BOOKS (id, title, genre, author) values (99, 'American Gun', 'Drama', 3);
insert into BOOKS (id, title, genre, author) values (100, 'Pillow of Death', 'Mystery|Thriller', 15);