insert into AUTHOR (id, first_name, last_name) values (1, 'Ingamar', 'Ragot');
insert into AUTHOR (id, first_name, last_name) values (2, 'Alair', 'Chalk');
insert into AUTHOR (id, first_name, last_name) values (3, 'Rube', 'Mulqueen');
insert into AUTHOR (id, first_name, last_name) values (4, 'Aida', 'Behling');
insert into AUTHOR (id, first_name, last_name) values (5, 'Wiley', 'Garz');
insert into AUTHOR (id, first_name, last_name) values (6, 'Alexina', 'Haswell');
insert into AUTHOR (id, first_name, last_name) values (7, 'Victoir', 'Everett');
insert into AUTHOR (id, first_name, last_name) values (8, 'Morten', 'Sprague');
insert into AUTHOR (id, first_name, last_name) values (9, 'Lev', 'Bastide');
insert into AUTHOR (id, first_name, last_name) values (10, 'Jasmina', 'McCleverty');
insert into AUTHOR (id, first_name, last_name) values (11, 'Shurlocke', 'Worters');
insert into AUTHOR (id, first_name, last_name) values (12, 'Georgy', 'Francais');
insert into AUTHOR (id, first_name, last_name) values (13, 'Tully', 'Gallahue');
insert into AUTHOR (id, first_name, last_name) values (14, 'Maritsa', 'Petroselli');
insert into AUTHOR (id, first_name, last_name) values (15, 'Krystal', 'Hamil');
insert into AUTHOR (id, first_name, last_name) values (16, 'Caro', 'Luxmoore');
insert into AUTHOR (id, first_name, last_name) values (17, 'Giselle', 'Costanza');
insert into AUTHOR (id, first_name, last_name) values (18, 'Christine', 'Angell');
insert into AUTHOR (id, first_name, last_name) values (19, 'Zebedee', 'Gleasane');
insert into AUTHOR (id, first_name, last_name) values (20, 'Nelli', 'Norcliff');
insert into BOOK (id, title, genre, author_id) values (1, 'Man-Thing', 'Action|Horror|Sci-Fi', 13);
insert into BOOK (id, title, genre, author_id) values (2, 'Thieves'' Highway', 'Drama|Film-Noir|Thriller', 16);
insert into BOOK (id, title, genre, author_id) values (3, 'Diplomatic Immunity (2009– )', 'Comedy', 13);
insert into BOOK (id, title, genre, author_id) values (4, 'Enough', 'Drama|Thriller', 15);
insert into BOOK (id, title, genre, author_id) values (5, 'Once Upon a Time in China II (Wong Fei-hung Ji Yi: Naam yi dong ji keung)', 'Action|Romance', 20);
insert into BOOK (id, title, genre, author_id) values (6, 'Silent Night, Bloody Night', 'Horror', 12);
insert into BOOK (id, title, genre, author_id) values (7, 'The Crowded Sky', 'Action|Adventure|Drama', 1);
insert into BOOK (id, title, genre, author_id) values (8, 'After Hours', 'Comedy|Thriller', 2);
insert into BOOK (id, title, genre, author_id) values (9, 'Suddenly', 'Crime|Drama|Film-Noir', 14);
insert into BOOK (id, title, genre, author_id) values (10, 'Revolutionary Girl Utena: Adolescence of Utena (a.k.a. Revolutionary Girl Utena the Movie) (Shoujo kakumei Utena: Adolescence mokushiroku)', 'Action|Adventure|Animation|Comedy|Drama|Fantasy|Romance', 16);
insert into BOOK (id, title, genre, author_id) values (11, 'Stendhal Syndrome, The (Sindrome di Stendhal, La)', 'Crime|Horror|Thriller', 11);
insert into BOOK (id, title, genre, author_id) values (12, 'Phantom of the Opera, The', 'Drama|Musical|Romance', 7);
insert into BOOK (id, title, genre, author_id) values (13, 'Coney Island', 'Comedy', 10);
insert into BOOK (id, title, genre, author_id) values (14, 'Soldier''s Story, A', 'Drama', 20);
insert into BOOK (id, title, genre, author_id) values (15, 'Metallica: Some Kind of Monster', 'Documentary', 4);
insert into BOOK (id, title, genre, author_id) values (16, 'Pageant', 'Documentary', 13);
insert into BOOK (id, title, genre, author_id) values (17, 'Hawaii', 'Drama', 20);
insert into BOOK (id, title, genre, author_id) values (18, 'Drona', 'Action|Adventure|Fantasy|Musical', 20);
insert into BOOK (id, title, genre, author_id) values (19, 'Man of the House', 'Comedy', 9);
insert into BOOK (id, title, genre, author_id) values (20, 'Bunnyman', 'Horror', 16);
insert into BOOK (id, title, genre, author_id) values (21, 'Flicker', 'Horror', 10);
insert into BOOK (id, title, genre, author_id) values (22, 'Babe, The', 'Drama', 9);
insert into BOOK (id, title, genre, author_id) values (23, 'Pursuit of Happiness, The', 'Drama', 18);
insert into BOOK (id, title, genre, author_id) values (24, 'Man of My Life, The (L''homme de sa vie)', 'Drama', 9);
insert into BOOK (id, title, genre, author_id) values (25, 'Hansel & Gretel', 'Children|Fantasy', 12);
insert into BOOK (id, title, genre, author_id) values (26, 'I Want to Be a Soldier', 'Drama', 7);
insert into BOOK (id, title, genre, author_id) values (27, 'Mount Head (Atama yama)', 'Animation|Comedy|Drama|Fantasy', 2);
insert into BOOK (id, title, genre, author_id) values (28, 'How to Steal a Million', 'Comedy|Crime|Romance', 13);
insert into BOOK (id, title, genre, author_id) values (29, 'Foxy Brown', 'Action|Crime|Drama', 14);
insert into BOOK (id, title, genre, author_id) values (30, 'Two Brothers (Deux frères)', 'Adventure|Children|Drama', 3);
insert into BOOK (id, title, genre, author_id) values (31, 'Wildcats', 'Comedy', 7);
insert into BOOK (id, title, genre, author_id) values (32, 'Chasing Liberty', 'Comedy|Romance', 2);
insert into BOOK (id, title, genre, author_id) values (33, 'G.I. Joe: The Rise of Cobra', 'Action|Adventure|Sci-Fi|Thriller', 5);
insert into BOOK (id, title, genre, author_id) values (34, 'Powaqqatsi', 'Documentary', 15);
insert into BOOK (id, title, genre, author_id) values (35, 'Tere Naam', 'Romance', 13);
insert into BOOK (id, title, genre, author_id) values (36, 'Without Lying Down: Frances Marion and the Power of Women in Hollywood', 'Documentary', 17);
insert into BOOK (id, title, genre, author_id) values (37, 'Gumball Rally, The', 'Adventure|Comedy', 17);
insert into BOOK (id, title, genre, author_id) values (38, 'Girl with Hyacinths', 'Drama|Mystery', 1);
insert into BOOK (id, title, genre, author_id) values (39, 'Stuff, The', 'Comedy|Horror|Mystery|Sci-Fi', 13);
insert into BOOK (id, title, genre, author_id) values (40, 'Great Locomotive Chase, The', 'Adventure|War', 19);
insert into BOOK (id, title, genre, author_id) values (41, 'Frozen North, The', 'Comedy', 19);
insert into BOOK (id, title, genre, author_id) values (42, 'Sign of Four, The', 'Crime|Mystery', 10);
insert into BOOK (id, title, genre, author_id) values (43, 'It Happened Tomorrow', 'Comedy|Fantasy', 11);
insert into BOOK (id, title, genre, author_id) values (44, 'Asterix & Obelix vs. Caesar (Astérix et Obélix contre César)', 'Adventure|Children|Comedy|Fantasy', 17);
insert into BOOK (id, title, genre, author_id) values (45, 'I Am Michael', 'Drama', 6);
insert into BOOK (id, title, genre, author_id) values (46, 'RiP: A Remix Manifesto', 'Documentary', 14);
insert into BOOK (id, title, genre, author_id) values (47, 'Bend of the River', 'Western', 3);
insert into BOOK (id, title, genre, author_id) values (48, 'Illegal', 'Drama', 14);
insert into BOOK (id, title, genre, author_id) values (49, 'Texas Chainsaw Massacre: The Beginning, The', 'Horror|Thriller', 4);
insert into BOOK (id, title, genre, author_id) values (50, 'Bag of Bones', 'Horror', 9);
insert into BOOK (id, title, genre, author_id) values (51, 'Why Worry?', 'Adventure|Comedy|Romance', 8);
insert into BOOK (id, title, genre, author_id) values (52, 'Innocent Man, An', 'Crime|Drama', 8);
insert into BOOK (id, title, genre, author_id) values (53, 'Love Affair, or the Case of the Missing Switchboard Operator (Ljubavni slucaj ili tragedija sluzbenice P.T.T.)', 'Drama', 19);
insert into BOOK (id, title, genre, author_id) values (54, 'Maborosi (Maboroshi no hikari)', 'Drama', 1);
insert into BOOK (id, title, genre, author_id) values (55, 'We Are from the Future (My iz budushchego)', 'Action|Drama|Fantasy', 19);
insert into BOOK (id, title, genre, author_id) values (56, 'Blues in the Night', 'Drama|Film-Noir|Musical', 2);
insert into BOOK (id, title, genre, author_id) values (57, 'Ballad of a Soldier (Ballada o soldate)', 'Drama|Romance|War', 19);
insert into BOOK (id, title, genre, author_id) values (58, 'Lion''s Den (Leonera)', 'Drama', 14);
insert into BOOK (id, title, genre, author_id) values (59, 'Play Misty for Me', 'Drama|Thriller', 6);
insert into BOOK (id, title, genre, author_id) values (60, 'Big Hero 6', 'Action|Animation|Comedy', 4);
insert into BOOK (id, title, genre, author_id) values (61, 'City of Women, The (Città delle donne, La)', 'Comedy|Drama', 13);
insert into BOOK (id, title, genre, author_id) values (62, 'Music Room, The (Jalsaghar)', 'Drama', 13);
insert into BOOK (id, title, genre, author_id) values (63, 'Worthless, The (Arvottomat)', 'Crime|Drama', 13);
insert into BOOK (id, title, genre, author_id) values (64, 'Prime of Miss Jean Brodie, The', 'Drama', 15);
insert into BOOK (id, title, genre, author_id) values (65, '8 Days to Premiere (8 päivää ensi-iltaan)', 'Comedy|Fantasy|Romance', 13);
insert into BOOK (id, title, genre, author_id) values (66, 'Touch', 'Drama|Fantasy|Romance', 8);
insert into BOOK (id, title, genre, author_id) values (67, 'Body of Lies', 'Action|Drama|Thriller', 5);
insert into BOOK (id, title, genre, author_id) values (68, 'Notre jour viendra', 'Drama', 5);
insert into BOOK (id, title, genre, author_id) values (69, 'Dead Times (Temps morts, Les)', 'Animation', 15);
insert into BOOK (id, title, genre, author_id) values (70, 'M. Hulot’s Holiday (Mr. Hulot''s Holiday) (Vacances de Monsieur Hulot, Les)', 'Comedy', 4);
insert into BOOK (id, title, genre, author_id) values (71, 'Blossoming of Maximo Oliveros, The (Ang pagdadalaga ni Maximo Oliveros)', 'Comedy|Drama', 12);
insert into BOOK (id, title, genre, author_id) values (72, 'Immortal Sergeant', 'Drama|War', 11);
insert into BOOK (id, title, genre, author_id) values (73, 'People I Know', 'Crime|Drama', 19);
insert into BOOK (id, title, genre, author_id) values (74, 'Hostage', 'Action|Crime|Drama|Thriller', 5);
insert into BOOK (id, title, genre, author_id) values (75, 'BURN-E', 'Adventure|Animation|Children|Sci-Fi', 16);
insert into BOOK (id, title, genre, author_id) values (76, 'Mikado, The', 'Comedy|Musical', 19);
insert into BOOK (id, title, genre, author_id) values (77, 'Marion Bridge', 'Drama', 12);
insert into BOOK (id, title, genre, author_id) values (78, 'Beats Being Dead (Dreileben - Etwas Besseres als den Tod)', 'Drama', 15);
insert into BOOK (id, title, genre, author_id) values (79, 'The Rabbi''s Cat (Le chat du rabbin)', 'Adventure|Animation', 7);
insert into BOOK (id, title, genre, author_id) values (80, 'Thrashin''', 'Action|Drama', 6);
insert into BOOK (id, title, genre, author_id) values (81, 'Ninja Scroll (Jûbei ninpûchô)', 'Action|Adventure|Animation|Fantasy', 15);
insert into BOOK (id, title, genre, author_id) values (82, 'Dark Horse (Voksne mennesker)', 'Comedy|Drama|Romance', 11);
insert into BOOK (id, title, genre, author_id) values (83, 'Cargo 200 (Gruz 200)', 'Drama', 7);
insert into BOOK (id, title, genre, author_id) values (84, 'Dracula', 'Horror|Romance', 11);
insert into BOOK (id, title, genre, author_id) values (85, 'Lunopolis', 'Sci-Fi', 7);
insert into BOOK (id, title, genre, author_id) values (86, 'Ladrón que roba a ladrón', 'Action|Adventure|Comedy|Crime', 18);
insert into BOOK (id, title, genre, author_id) values (87, 'Kid Stays in the Picture, The', 'Documentary', 15);
insert into BOOK (id, title, genre, author_id) values (88, 'Call of Cthulhu, The', 'Horror|Thriller', 19);
insert into BOOK (id, title, genre, author_id) values (89, 'Grotesque', 'Horror', 13);
insert into BOOK (id, title, genre, author_id) values (90, 'Tale of the Mummy', 'Adventure|Fantasy|Horror', 20);
insert into BOOK (id, title, genre, author_id) values (91, 'American Perfekt', 'Crime|Drama|Thriller', 2);
insert into BOOK (id, title, genre, author_id) values (92, 'Starship Invasions', 'Sci-Fi', 10);
insert into BOOK (id, title, genre, author_id) values (93, 'Last of the High Kings, The (a.k.a. Summer Fling)', 'Comedy|Drama', 18);
insert into BOOK (id, title, genre, author_id) values (94, 'Night of the Demons', 'Horror', 9);
insert into BOOK (id, title, genre, author_id) values (95, 'St. Ives', 'Crime|Mystery|Thriller', 5);
insert into BOOK (id, title, genre, author_id) values (96, 'Second Man, The (O Defteros Andras)', 'Drama', 4);
insert into BOOK (id, title, genre, author_id) values (97, 'Roadkill (a.k.a. Roadkill: Move or Die)', 'Drama', 17);
insert into BOOK (id, title, genre, author_id) values (98, 'Butcher Boys (Bone Boys)', 'Action|Comedy|Horror|Thriller', 15);
insert into BOOK (id, title, genre, author_id) values (99, 'Two Family House', 'Drama', 10);
insert into BOOK (id, title, genre, author_id) values (100, 'Pulp Fiction', 'Comedy|Crime|Drama|Thriller', 9);